# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - build:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
           - .env
           - package.json
           - node_modules
           - src
           - build
           - config
           - server
           - Dockerfile
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.14.37
            # Login to ecr and docker login
            aws_login=`aws ecr get-login --no-include-email --region eu-west-2`
            eval $aws_login
            # Docker build, tag and push
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t consents .
            docker tag consents 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:$TAG
            docker tag consents:latest 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:latest
            docker push 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:$TAG
            docker push 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:latest

            docker tag consents:latest 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:latest
            docker tag 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:latest 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:sit
            docker push 592759841913.dkr.ecr.eu-west-2.amazonaws.com/consents:sit

            aws ecs update-service --cluster portfolio-cluster --service portfolio-service --force-new-deployment --region eu-west-1
            
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
